Add -lpthread -ldl to link executable/tests
The new binutils-2.23 based linker in
prebuilts/gcc/linux-x86/host/x86_64-linux-glibc2.11-4.6
no longer implicity adds dependencies on *so an executable needs.
eg.

  ld -o barrier_test barrier_test.o common_runtime_test.o ... -lartd

produces error messages read

  art/runtime/thread-inl.h:43: error: undefined reference to 'pthread_getspecific'
  art/runtime/common_runtime_test.h:219: error: undefined reference to 'dlsym'
  external/gtest/src/../include/gtest/internal/gtest-port.h:1482: error: undefined reference to 'pthread_getspecific'

because libartd.so DT_NEEDED libdl.so and libpthread.so, and new linker no longer
implicitly add both to dependencies.  Explicitly add -lpthread -ldl to fix the issue

Change-Id: Ic29c68480b2ed55d282be949640b9158411f213d